---
kind: pipeline
name: default

steps:
  - name: build
    image: golang:1.17-alpine
    commands:
      - GOOS=linux CGO_ENABLED=0 go build -ldflags="-s -w" -o wecomchan wecomchan.go

  - name: build-image
    image: plugins/docker
    settings:
      username: lyj0309
      password:
        from_secret: docker_password
      repo: lyj0309/drone-wecomchan
      auto_tag: true

  - name: sendmsg
    image: lyj0309/drone-wecomchan
    settings:
      key:
        from_secret: wecomchan_key
      path: https://service-lqj0ehgj-1256627948.bj.apigw.tencentcs.com/release/wecomchan
      msg: build_success
